# Testnet & MAINNET
from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

MODE = "DEVELOPMENT"
# Close all open positions and orders
ABORT_ALL_POSITIONS = False
# show co-intergated pairs
FIND_COINTERGRATED = True
# Place trades
PLACE_TRADES = True

# RESOLUTION
RESOLUTION = "1HOUR"

# STATS WINDOW
STAT_WINDOW = 21

# THRESHOLDS - OPENING
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# THRESHOLDS - CLOSING
CLOSE_AT_ZSCORE_CROSS = True

ETH_ADDRESS = "0x1Dd092B79C0c340A0EBd9B90ec190D540091Ed24"
ETH_PK = "0x12cad9378906485295cd6e9511accdede95819969d5ec19e3dea0d8eec910e60"


STARK_PK_TESTNET = config("STARK_PK_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

STARK_PK_MAINNET = config("STARK_PK_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# Export
STARK_PK = STARK_PK_MAINNET if MODE == "PRODUCTION" else STARK_PK_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = (
    DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
)
DYDX_API_PASSPHRASE = (
    DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET
)

HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI


MAINNET = "https://eth-mainnet.g.alchemy.com/v2/58NqO7pxLMquPumNVrDp5zKUUG_OyQfw"
TESTNET = "https://eth-goerli.g.alchemy.com/v2/d6_ZXhjTNOhS9YwxsRb80autxqrsCxyI"
PROVIDER = MAINNET if MODE == "PRODUCTION" else TESTNET
